name: talib-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ta-lib
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - requests>=2.28
  - pip
  - pip:
      - yfinance>=0.2.18
