name: Quick Scan Runner (Multiple Times a Day)

on:
  schedule:
    - cron: '35 13 * * 1-5'  # 9:35 AM EST
    - cron: '00 17 * * 1-5'  # 1:00 PM EST  
    - cron: '55 19 * * 1-5'  # 3:55 PM EST
  workflow_dispatch:

jobs:
  run-quick-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run Quick Scan
        run: python hybrid_analyzer.py quick # <-- لاحظ كيف نمرر الوضع هنا
      - name: Commit Quick Scan Results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update quick scan analysis'
          file_pattern: 'quick_analysis.json'
